banner:
  name:
    en: OpenStreetMap Belgium
    nl: OpenStreetMap BelgiÃ«
    fr: OpenStreetMap Belgique
  welcome:
    en: Welcome to OSM-BE!
    nl: Welkom bij OSM-BE!
    fr: Bienvenue chez OSM-BE
  byline:
    en: This is the home of the OpenStreetMap community in Belgium!
    nl: "&nbsp;"
    fr: "&nbsp;"
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
twitter:
  username: osm_be
url: http://osm.be
description: OpenStreetMap Belgium community website
social:
  name: OpenStreetMap Belgium
  links:
    - https://twitter.com/osm_be
    - https://www.facebook.com/groups/1419016881706058/
    - https://github.com/osmbe
